import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SparklesIcon from "@/components/SparklesIcon";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Video Caption Generation",
  description: "Generated by Parth",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to text-white min-h-screen"}>
        <main className="p-4 max-w-2xl mx-auto">
            <header className="flex justify-between my-8">
                <Link href="/" className="flex gap-1">
                  <SparklesIcon/>
                  <span>Caption Generation</span>
                </Link>
                <nav className="flex gap-6 text-white/80">
                  <Link href="/Home">Home</Link>
                  <Link href="/services">Services</Link>
                  <a href="mailto:parth.wattamwar@mitaoe.ac.in">About</a>
                </nav>
            </header>
          {children}
        </main>
      </body>
    </html>
  );
}
